import random

#This will produce a random whole number between 1 and 10 (inclusive).
#random_integer = random.randint(1,10)
#print(random_integer)

# You can generate a random number between 0.0 (inclusive) and 1.0 (not inclusive) using the following code from the random module:
#random_number_0_to_1 = random.random()
#print(random_number_0_to_1)

#You can expand the range of random numbers generated by this method using multiplication.
### Will generate a random number between 0 and 40.
#random_number_0_to_1 = random.random() * 40
#print(random_number_0_to_1)

#This will generate a random floating point number between 1 and 10.
#random_float = random.uniform(1, 10)
#print(random_float)

random_heads_or_tails = random.randint(0, 2)
#print(random_heads_or_tails)
if random_heads_or_tails == 0:
    print("Heads")
else:
    print("Tails")
